version: "3.9"

services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb_vidracaria
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_empresa001
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_vidracaria
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_USER: user
      PMA_PASSWORD: user123
      UPLOAD_LIMIT: 128M
    ports:
      - "8080:80"
